// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpz2gUGRm5ArWaWz-6hUxe_RRmheIE9II',
    appId: '1:608233040494:web:979e702bd2d460b4bc147f',
    messagingSenderId: '608233040494',
    projectId: 'flutterutility',
    authDomain: 'flutterutility.firebaseapp.com',
    storageBucket: 'flutterutility.appspot.com',
    measurementId: 'G-78F9ZSHVMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVjI9pshKI320B9D0LxSN9St7onAfJgeE',
    appId: '1:608233040494:android:bce3855bac9cc8c4bc147f',
    messagingSenderId: '608233040494',
    projectId: 'flutterutility',
    storageBucket: 'flutterutility.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Z3vjW6Qi46GAoH_ILOGLGSjAu1K27BU',
    appId: '1:608233040494:ios:6133cf0edd5e6979bc147f',
    messagingSenderId: '608233040494',
    projectId: 'flutterutility',
    storageBucket: 'flutterutility.appspot.com',
    iosBundleId: 'com.example.flutterutility',
  );
}
